#!/bin/bash
# Test Railway build by checking deployment logs

echo "🔍 Sprawdzanie Railway build logs..."
echo ""
echo "Uruchom to polecenie aby zobaczyć logi Railway:"
echo ""
echo "  railway logs --deployment"
echo ""
echo "Szukaj w logach:"
echo "  ✅ '📥 Downloading Microsoft Core Fonts'"
echo "  ✅ '✅ Installed XX Microsoft Core Fonts'"
echo "  ✅ '✓ Font detection: XXX+ font families found'"
echo "  ✅ '✓ Loaded font: arialbd.ttf from /usr/share/fonts/truetype/msttcorefonts'"
echo ""
echo "Jeśli zobaczysz '⚠ No TTF files found':"
echo "  → SourceForge był niedostępny podczas buildu"
echo "  → Aplikacja użyje Liberation fonts (fallback)"
echo "  → Nadal będzie działać, ale może mieć różnice w metrykach"
echo ""
